version: '2'
services:

  # Cerebro Elasticsearch client
  cerebro:
    build: .
    ports:
      - "9001:9000"
    networks:
      - app_net

  # Elasticsearch cluster
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    environment:
      ES_JAVA_OPTS: -Xms750m -Xmx750m
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app_net

  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.0
    ports:
      - "5602:5601"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
